Modernised the script, using the same variables as in other scripts, using the lemma-extract.sh script in gtcore, and using better grep expressions for failed generations. Also added both analysis and generation of the missing lemmas, to aid in debugging adjective lemmas.

diff --git a/test/src/morphology/test-adj-generation.sh.in b/test/src/morphology/test-adj-generation.sh.in
--- a/test/src/morphology/test-adj-generation.sh.in
+++ b/test/src/morphology/test-adj-generation.sh.in
@@ -1,18 +1,45 @@
 #!/bin/bash
+# @configure_input@
+
+# Automake interprets the exit status as follows:
+# - an exit status of 0 will denote a success
+# - an exit status of 77 a skipped test
+# - an exit status of 99 a hard error
+# - any other exit status will denote a failure.
 
 # Dette skriptet tester at nesten alle lemmaene i
 # $GTHOME/langs/sma/src/morphology/stems/adjectives.lexc kan genereres.
-# De som ikke kan genereres, kopieres til missingAdjLemmas.txt
+# De som ikke kan genereres, kopieres til missing_adjectives_lemmas.txt
 
 ###### Variables: #######
-sourcefile=${srcdir}/../../../src/morphology/stems/adjectives.lexc
-generatorfile=./../../../src/generator-gt-norm
-resultfile=missingAdjLemmas
+POS=adjectives
+### in ###
+source_file=${srcdir}/../../../src/morphology/stems/${POS}.lexc
+generator_file=./../../../src/generator-gt-norm
+analyser_file=./../../../src/analyser-gt-norm
 
-# Check that the source file exists:
-if [ ! -f "$sourcefile" ]; then
-	echo Source file not found: $sourcefile
-	exit 1
+### out ###
+all_lemmas=./filtered-all-${POS}.txt
+attr_lemmas=./filtered-attr-${POS}.txt
+pred_lemmas=./filtered-pred-${POS}.txt
+comp_lemmas=./filtered-comp-${POS}.txt
+supr_lemmas=./filtered-supr-${POS}.txt
+lemma_files="$attr_lemmas $pred_lemmas $comp_lemmas $supr_lemmas"
+generated_all_lemmas=./generated-all-${POS}
+generated_attr_lemmas=./generated-attr-${POS}
+generated_pred_lemmas=./generated-pred-${POS}
+generated_comp_lemmas=./generated-comp-${POS}
+generated_supr_lemmas=./generated-supr-${POS}
+result_file=missing_${POS}_lemmas
+gen_result_file=generated_missing_${POS}_lemmas
+ana_result_file=analysed_missing_${POS}_lemmas
+
+# SKIP if source file does not exist:
+if [ ! -f $source_file ]; then
+    echo
+    echo "*** Warning: Source file $source_file not found."
+    echo
+    exit 77
 fi
 
 # Use autotools mechanisms to only run the configured fst types in the tests:
@@ -21,7 +48,7 @@ fsttype=
 @CAN_XFST_TRUE@fsttype="$fsttype xfst"
 
 # Exit if both hfst and xerox have been shut off:
-if test -z "$fsttype"; then
+if test -z "$fsttype" ; then
     echo "All transducer types have been shut off at configure time."
     echo "Nothing to test. Skipping."
     exit 77
@@ -30,92 +57,134 @@ fi
 # Get external Mac editor for viewing failed results from configure:
 EXTEDITOR=@SEE@
 
-###### Extraction: #######
-### Regular adjectives:
-grep ";" $sourcefile | grep -v "^\!" | sed 's/\([^%]\)!.*/\1/' \
-	| egrep -v "(PRED|CASE| MES|EVTEBE)" | tr ":+" " " | cut -d " " -f1 \
-	| tr -d "#" | sort -u | grep -v '^$' > adjs.tmp.txt
-### Adjectives with no attr form, ie only pred form:
-grep ";" $sourcefile | grep -v "^\!" | sed 's/\([^%]\)!.*/\1/' \
-	| egrep "(PRED|CASE)" | tr ":+" " " | cut -d " " -f1 | tr -d "#" \
-	| sort -u > predadjs.txt
-### Adjectives with only comparative forms:
-grep ";" $sourcefile | grep -v "^\!" | sed 's/\([^%]\)!.*/\1/' \
-	| grep "EVTEBE" | tr ":+" " " | cut -d " " -f1 | tr -d "#" \
-	| sort -u > compladjs.txt
-### Adjectives with only superlative forms:
-grep ";" $sourcefile | grep -v "^\!" | sed 's/\([^%]\)!.*/\1/' \
-	| grep " MES" | tr ":+" " " | cut -d " " -f1 | tr -d "#" \
-	| sort -u > superladjs.txt
+##### Extract lemmas - add additional egrep pattern as parameters: #####
+##### --include "(pattern1|pattern2|...)"                          #####
+##### --exclude "(pattern1|pattern2|...)"                          #####
+# Regular attributive lemmas:
+@GTCORE@/scripts/extract-lemmas.sh \
+    --exclude "(PRED|CASE| MES|EVTEBE)" \
+    $source_file > $attr_lemmas
+
+# Predicative lemmas:
+@GTCORE@/scripts/extract-lemmas.sh \
+    --include "(PRED|CASE)" \
+    $source_file > $pred_lemmas
+
+# Comparative lemmas:
+@GTCORE@/scripts/extract-lemmas.sh \
+    --include "(EVTEBE)" \
+    $source_file > $comp_lemmas
+
+# Superlative lemmas:
+@GTCORE@/scripts/extract-lemmas.sh \
+    --include "( MES)" \
+    $source_file > $supr_lemmas
 
 ###### Start testing: #######
 transducer_found=0
 Fail=0
 
+# The script tests both Xerox and Hfst transducers if available:
 for f in $fsttype; do
-	if [ $f == "xfst" ]; then
-		lookuptool="@LOOKUP@ -q -flags mbTT"
-		suffix="xfst"
-	elif [ $f == "hfst" ]; then
-		lookuptool="@HFST_OPTIMIZED_LOOKUP@ -q"
-		suffix="hfstol"
-	else
-	    Fail=1
-		echo "Unknown fst type!"
-	    echo "$f - FAIL"
-	    continue
-	fi
-	if [ -f "$generatorfile.$suffix" ]; then
-		let "transducer_found += 1"
+    if [ $f == "xfst" ]; then
+        lookup_tool="@LOOKUP@ -q -flags mbTT"
+        suffix="xfst"
+    elif [ $f == "hfst" ]; then
+        lookup_tool="@HFST_OPTIMIZED_LOOKUP@ -q"
+        suffix="hfstol"
+    else
+        Fail=1
+        printf "ERROR: Unknown fst type! "
+        echo "$f - FAIL"
+        continue
+    fi
+    if [ -f "$generator_file.$suffix" ]; then
+        let "transducer_found += 1"
 
-#### First we try to generate the regular adjectives:
-		sed 's/$/+A+Attr/' adjs.tmp.txt | $lookuptool $generatorfile.$suffix \
-			| cut -f2 | grep -v "A+" | grep -v "^$" | sort -u > analadjs.$f.txt 
+###### Test lemma generation: #######
+        # generate lemmas in attr, extract the resulting generated
+        # lemma, store it:
+        sed 's/$/+A+Attr/' $attr_lemmas \
+            | $lookup_tool $generator_file.$suffix \
+            | fgrep -v "+?" | grep -v "^$" | cut -f2 | sort -u \
+            > $generated_attr_lemmas.$f.txt 
 
-#### Then we try to generate the predicate-only adjectives:
-		sed 's/$/+A+Sg+Nom/' predadjs.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs.$f.txt 
+        # generate lemmas in singular pred, extract the resulting generated
+        # lemma, store it:
+        sed 's/$/+A+Sg+Nom/' $pred_lemmas \
+            | $lookup_tool $generator_file.$suffix \
+            | fgrep -v "+?" | grep -v "^$" | cut -f2 | sort -u \
+            > $generated_pred_lemmas.$f.txt 
 
-#### Then we try to generate the predicate-only adjectives:
-		sed 's/$/+A+Superl+Sg+Nom/' superladjs.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs.$f.txt 
+        # generate lemmas in comparative, extract the resulting generated
+        # lemma, store it:
+        sed 's/$/+A+Comp+Sg+Nom/' $comp_lemmas \
+            | $lookup_tool $generator_file.$suffix \
+            | fgrep -v "+?" | grep -v "^$" | cut -f2 | sort -u \
+            > $generated_comp_lemmas.$f.txt 
 
-#### Then we try to generate the predicate-only adjectives:
-		sed 's/$/+A+Comp+Sg+Nom/' compladjs.txt \
-			| $lookuptool $generatorfile.$suffix | cut -f2 \
-			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs.$f.txt 
+        # generate lemmas in superlative, extract the resulting generated
+        # lemma, store it:
+        sed 's/$/+A+Superl+Sg+Nom/' $supr_lemmas \
+            | $lookup_tool $generator_file.$suffix \
+            | fgrep -v "+?" | grep -v "^$" | cut -f2 | sort -u \
+            > $generated_supr_lemmas.$f.txt 
 
-		cat predadjs.txt superladjs.txt compladjs.txt >> adjs.tmp.txt
-		sort -u adjs.tmp.txt | grep -v '^$' > adjs.txt
-		sort -u -o analadjs.$f.txt analadjs.$f.txt 
-		comm -23 adjs.txt analadjs.$f.txt > $resultfile.$f.txt
 
-		# if at least one word is found, the test failed, and the list of failed
-		# lemmas is opened in SubEthaEdit:
-		if [ -s $resultfile.$f.txt ]; then
-			# Only open the failed lemmas in see if @SEE@ is defined:
-			if [ "$EXTEDITOR" ]; then
-				$EXTEDITOR $resultfile.$f.txt
-			fi
-		    Fail=1
-		    echo "$f - FAIL"
-		    continue
-		fi
-	    echo "$f - PASS"
-	fi
+###### Collect results, and generate debug info if FAIL: #######
+        # Sort and compare original input with resulting output - the diff is
+        # used to generate lemmas which are opened in SEE:
+        cat $lemma_files | sort -u > $all_lemmas
+        cat $generated_attr_lemmas.$f.txt \
+            $generated_pred_lemmas.$f.txt \
+            $generated_comp_lemmas.$f.txt \
+            $generated_supr_lemmas.$f.txt \
+            | sort -u > $generated_all_lemmas.$f.txt
+        comm -23 $all_lemmas $generated_all_lemmas.$f.txt > $result_file.$f.txt
+
+        # Open the diff file in SubEthaEdit (if there is a diff):
+        if [ -s $result_file.$f.txt ]; then
+            grep -v '^$' $result_file.$f.txt \
+              | sed 's/$/+A+Attr/' \
+              | $lookup_tool $generator_file.$suffix \
+              > $gen_result_file.$f.txt
+            # If we have an analyser, analyse the missing lemmas as well:
+            if test -e $analyser_file.$suffix ; then
+                grep -v '^$' $result_file.$f.txt \
+                  | $lookup_tool $analyser_file.$suffix \
+                  > $ana_result_file.$f.txt
+            fi
+            # Only open the failed lemmas in see if @SEE@ is defined:
+            if [ "$EXTEDITOR" ]; then
+                $EXTEDITOR $result_file.$f.txt
+                $EXTEDITOR $gen_result_file.$f.txt
+                $EXTEDITOR $ana_result_file.$f.txt
+            else
+                echo "There where problem lemmas. Details in:"
+                echo "* $result_file.$f.txt    "
+                echo "* $gen_result_file.$f.txt"
+                echo "* $ana_result_file.$f.txt"
+            fi
+            Fail=1
+            echo "$f - FAIL"
+            continue
+        fi
+        echo "$f - PASS"
+    fi
 done
 
-# Delete temporary files:
-rm -f *adjs
+# When done, remove the generated data files:
+rm -f $lemma_files $all_lemmas ./generated*.txt
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
-	exit 1
+    exit 1
 fi
 
 if [ $transducer_found -eq 0 ]; then
-    echo No transducer found
-    exit 1
+    echo ERROR: No transducer found
+    exit 77
 fi
+
+# If the test succeeded, remove the result files:
+rm -f $result_file.*.txt
