Multiple changes to make sure only the tests for the transducer types that have been turned on in the configuration are run. Ie, if hfst is off, don't run the hfst transducer tests.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/sma@66169 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/test-verb-generation.sh.in b/test/src/morphology/test-verb-generation.sh.in
--- a/test/src/morphology/test-verb-generation.sh.in
+++ b/test/src/morphology/test-verb-generation.sh.in
@@ -14,62 +14,74 @@ if [ ! -f "$sourcefile" ]; then
 	exit 1
 fi
 
+# Use autotools mechanisms to only run the configured fst types in the tests:
+fsttype=
+@CAN_HFST_TRUE@fsttype="$fsttype hfst"
+@CAN_XFST_TRUE@fsttype="$fsttype xfst"
+
+# Exit if both hfst and xerox have been shut off:
+if [ -z $fsttype ]; then
+    echo "All transducer types have been shut off at configure time."
+    echo "Nothing to test. Skipping."
+    exit 77
+fi
+
 ###### Extraction: #######
 grep ";" $sourcefile | grep -v "^\!" \
 	| egrep -v '(STRAYFORMS|ENDLEX|+V)' | tr ":+" " " | cut -d " " -f1 \
-	| tr -d "#" | sort -u > verbs
+	| tr -d "#" | sort -u > verbs.txt
 
 ###### Start testing: #######
 transducer_found=0
 Fail=0
 
-for f in  .xfst .hfst; do
-	if [ $f == ".xfst" ]; then
+for f in $fsttype; do
+	if [ $f == "xfst" ]; then
 		lookuptool="@LOOKUP@ -q -flags mbTT"
-		fsttype=xfst
-	else
+	elif [ $f == "hfst" ]; then
 		lookuptool="@HFST_LOOKUP@ -q"
-		fsttype=hfst
+	else
+	    Fail=1
+		echo "Unknown fst type!"
+	    echo "$f - FAIL"
+	    continue
 	fi
-	if [ -f "$generatorfile$f" ]; then
+	if [ -f "$generatorfile.$f" ]; then
 		let "transducer_found += 1"
 
-# Remove old generated files - don't mix Xerox and HFST test results:
-		rm -f analverbs
-
 #### First we try to generate the infinitives:
-		sed 's/$/+V+Inf/' verbs \
-			| $lookuptool $generatorfile$f \
-			| cut -f2 | grep -v "V+" | grep -v "^$" | sort -u > analverbs
+		sed 's/$/+V+Inf/' verbs.txt \
+			| $lookuptool $generatorfile.$f \
+			| cut -f2 | grep -v "V+" | grep -v "^$" | sort -u > analverbs.$f.txt
 
 #### Kvifor trekkjer vi ut +N-analyser, og genererer substantiv i ein verb-test?
-		cat verbs | sed 's/$/+V+Inf/' \
-			| $lookuptool $generatorfile$f \
+		cat verbs.txt | sed 's/$/+V+Inf/' \
+			| $lookuptool $generatorfile.$f \
 			| cut -f2 | grep "N+" | cut -d "+" -f1 | sed 's/$/+N+Pl+Nom/' \
-			| $lookuptool $generatorfile$f | cut -f2 \
-			| grep -v "^$" >> analverbs 
+			| $lookuptool $generatorfile.$f | cut -f2 \
+			| grep -v "^$" >> analverbs.$f.txt
 
-#### Sort uniq resultatet
-		sort -u -o analverbs analverbs
+#### Sort & uniq resultatet
+		sort -u -o analverbs.$f.txt analverbs.$f.txt
 
 #### Samanlikne inndata med utdata:
-		comm -23 verbs analverbs > $resultfile$f.txt
+		comm -23 verbs.txt analverbs.$f.txt > $resultfile.$f.txt
 
 		# if at least one word is found, the test failed, and the list of failed
 		# lemmas is opened in SubEthaEdit:
-		if [ `wc -w $resultfile$f.txt | tr -s ' ' | cut -d' ' -f2` -gt 0 ]
+		if [ `wc -w $resultfile.$f.txt | tr -s ' ' | cut -d' ' -f2` -gt 0 ]
 		then
-			see $resultfile$f.txt
+			see $resultfile.$f.txt
 		    Fail=1
-		    echo "$fsttype - FAIL"
+		    echo "$f - FAIL"
 		    continue
 		fi
-	    echo "$fsttype - PASS"
+	    echo "$f - PASS"
 	fi
 done
 
 # Delete temporary files:
-rm *verbs
+rm *verbs.*.txt
 
 # At least one of the Xerox or HFST tests failed:
 if [ "$Fail" = "1" ]; then
