Multiple changes to make sure only the tests for the transducer types that have been turned on in the configuration are run. Ie, if hfst is off, don't run the hfst transducer tests.

diff --git a/test/src/morphology/test-adj-generation.sh.in b/test/src/morphology/test-adj-generation.sh.in
--- a/test/src/morphology/test-adj-generation.sh.in
+++ b/test/src/morphology/test-adj-generation.sh.in
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Dette skriptet tester at nesten alle lemmaene i
-# $GTHOME/newinfra/langs/sma/src/morphology/stems/adjectives.lexc kan genereres.
+# $GTHOME/langs/sma/src/morphology/stems/adjectives.lexc kan genereres.
 # De som ikke kan genereres, kopieres til missingAdjLemmas.txt
 
 ###### Variables: #######
@@ -15,76 +15,88 @@ if [ ! -f "$sourcefile" ]; then
 	exit 1
 fi
 
+# Use autotools mechanisms to only run the configured fst types in the tests:
+fsttype=
+@CAN_HFST_TRUE@fsttype="$fsttype hfst"
+@CAN_XFST_TRUE@fsttype="$fsttype xfst"
+
+# Exit if both hfst and xerox have been shut off:
+if [ -z $fsttype ]; then
+    echo "All transducer types have been shut off at configure time."
+    echo "Nothing to test. Skipping."
+    exit 77
+fi
+
 ###### Extraction: #######
 ### Regular adjectives:
 grep ";" $sourcefile | grep -v "^\!" \
 	| egrep -v "(PRED|CASE| MES|EVTEBE)" | tr ":+" " " | cut -d " " -f1 \
-	| tr -d "#" | sort -u > adjs
+	| tr -d "#" | sort -u > adjs.txt
 ### Adjectives with no attr form, ie only pred form:
 grep ";" $sourcefile | grep -v "^\!" \
 	| egrep "(PRED|CASE)" | tr ":+" " " | cut -d " " -f1 | tr -d "#" \
-	| sort -u > predadjs
+	| sort -u > predadjs.txt
 ### Adjectives with only comparative forms:
 grep ";" $sourcefile | grep -v "^\!" \
 	| grep "EVTEBE" | tr ":+" " " | cut -d " " -f1 | tr -d "#" \
-	| sort -u > compladjs
+	| sort -u > compladjs.txt
 ### Adjectives with only superlative forms:
 grep ";" $sourcefile | grep -v "^\!" \
 	| grep " MES" | tr ":+" " " | cut -d " " -f1 | tr -d "#" \
-	| sort -u > superladjs
+	| sort -u > superladjs.txt
 
 ###### Start testing: #######
 transducer_found=0
 Fail=0
 
-for f in  .xfst .hfst; do
-	if [ $f == ".xfst" ]; then
+for f in $fsttype; do
+	if [ $f == "xfst" ]; then
 		lookuptool="@LOOKUP@ -q -flags mbTT"
-		fsttype=xfst
-	else
+	elif [ $f == "hfst" ]; then
 		lookuptool="@HFST_LOOKUP@ -q"
-		fsttype=hfst
+	else
+	    Fail=1
+		echo "Unknown fst type!"
+	    echo "$f - FAIL"
+	    continue
 	fi
-	if [ -f "$generatorfile$f" ]; then
+	if [ -f "$generatorfile.$f" ]; then
 		let "transducer_found += 1"
 
-# Remove old generated files - don't mix Xerox and HFST test results:
-		rm -f analadjs
-
 #### First we try to generate the regular adjectives:
-		sed 's/$/+A+Attr/' adjs | $lookuptool $generatorfile$f \
-			| cut -f2 | grep -v "A+" | grep -v "^$" | sort -u > analadjs 
+		sed 's/$/+A+Attr/' adjs.txt | $lookuptool $generatorfile.$f \
+			| cut -f2 | grep -v "A+" | grep -v "^$" | sort -u > analadjs.$f.txt 
 
 #### Then we try to generate the predicate-only adjectives:
-		sed 's/$/+A+Sg+Nom/' predadjs \
-			| $lookuptool $generatorfile$f | cut -f2 \
-			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs 
+		sed 's/$/+A+Sg+Nom/' predadjs.txt \
+			| $lookuptool $generatorfile.$f | cut -f2 \
+			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs.$f.txt 
 
 #### Then we try to generate the predicate-only adjectives:
-		sed 's/$/+A+Superl+Sg+Nom/' superladjs \
-			| $lookuptool $generatorfile$f | cut -f2 \
-			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs 
+		sed 's/$/+A+Superl+Sg+Nom/' superladjs.txt \
+			| $lookuptool $generatorfile.$f | cut -f2 \
+			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs.$f.txt 
 
 #### Then we try to generate the predicate-only adjectives:
-		sed 's/$/+A+Comp+Sg+Nom/' compladjs \
-			| $lookuptool $generatorfile$f | cut -f2 \
-			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs 
+		sed 's/$/+A+Comp+Sg+Nom/' compladjs.txt \
+			| $lookuptool $generatorfile.$f | cut -f2 \
+			| grep -v "A+" | grep -v "^$" | sort -u >> analadjs.$f.txt 
 
-		cat predadjs superladjs compladjs >> adjs
-		sort -u -o adjs adjs 
-		sort -u -o analadjs analadjs 
-		comm -23 adjs analadjs > $resultfile$f.txt
+		cat predadjs.txt superladjs.txt compladjs.txt >> adjs.txt
+		sort -u -o adjs.txt adjs.txt 
+		sort -u -o analadjs.$f.txt analadjs.$f.txt 
+		comm -23 adjs.txt analadjs.$f.txt > $resultfile.$f.txt
 
 		# if at least one word is found, the test failed, and the list of failed
 		# lemmas is opened in SubEthaEdit:
-		if [ `wc -w $resultfile$f.txt | tr -s ' ' | cut -d' ' -f2` -gt 0 ]
+		if [ `wc -w $resultfile.$f.txt | tr -s ' ' | cut -d' ' -f2` -gt 0 ]
 		then
-			see $resultfile$f.txt
+			see $resultfile.$f.txt
 		    Fail=1
-		    echo "$fsttype - FAIL"
+		    echo "$f - FAIL"
 		    continue
 		fi
-	    echo "$fsttype - PASS"
+	    echo "$f - PASS"
 	fi
 done
 
