Updated comments and some feedback printouts, to bring the script in line with other scripts.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/langs/sma@109522 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/src/morphology/test-propernoun-generation.sh.in b/test/src/morphology/test-propernoun-generation.sh.in
--- a/test/src/morphology/test-propernoun-generation.sh.in
+++ b/test/src/morphology/test-propernoun-generation.sh.in
@@ -1,8 +1,19 @@
 #!/bin/bash
+# @configure_input@
+
+# Automake interprets the exit status as follows:
+# - an exit status of 0 will denote a success
+# - an exit status of 77 a skipped test
+# - an exit status of 99 a hard error
+# - any other exit status will denote a failure.
+
+# To run this test script only, do:
+#
+# make check TESTS=generate-propernoun-lemmas.sh
 
 # Dette skriptet tester at alle lemmaene i
-# $GTHOME/langs/sma/src/morphology/stems/propernouns.lexc kan genereres.
-# De som ikke kan genereres, kopieres til missingProperLemmas.txt
+# $GTHOME/langs/sma/src/morphology/generated_files/smi-sma-propernouns.lexc kan
+# genereres. De som ikke kan genereres, kopieres til missingProperLemmas.txt
 
 ###### Variables: #######
 ### in ###
@@ -18,10 +29,12 @@ generated_attr_lemmas=./generated-attr-proper
 missing_file=missing_proper_lemmas
 anal_missing_file=Analysed_missing_proper_lemmas
 
-# Check that the source file exists:
+# SKIP if source file does not exist:
 if [ ! -f "$source_file" ]; then
-	echo Source file not found: $source_file
-	exit 1
+    echo
+    echo "*** Warning: Source file $source_file not found."
+    echo
+    exit 77
 fi
 
 # Use autotools mechanisms to only run the configured fst types in the tests:
@@ -39,7 +52,9 @@ fi
 # Get external Mac editor for viewing failed results from configure:
 EXTEDITOR=@SEE@
 
-###### Extraction: #######
+##### Extract lemmas - add additional egrep pattern as parameters: #####
+##### --include "(pattern1|pattern2|...)"                          #####
+##### --exclude "(pattern1|pattern2|...)"                          #####
 # Extract all lemmas except hardcoded Attr:
 @GTCORE@/scripts/extract-lemmas.sh \
 	--exclude "(Attr)" \
@@ -54,6 +69,7 @@ EXTEDITOR=@SEE@
 transducer_found=0
 Fail=0
 
+# The script tests both Xerox and Hfst transducers if available:
 for f in $fsttype; do
 	if [ $f == "xfst" ]; then
 		lookuptool="@LOOKUP@ -q -flags mbTT"
@@ -63,7 +79,7 @@ for f in $fsttype; do
 		suffix="hfstol"
 	else
 	    Fail=1
-		echo "Unknown fst type!"
+		printf "ERROR: Unknown fst type! "
 	    echo "$f - FAIL"
 	    continue
 	fi
@@ -117,7 +133,7 @@ for f in $fsttype; do
 	fi
 done
 
-# Delete temporary files:
+# When done, remove the generated data file:
 rm -f $lemmas $attr_lemmas $generated_lemmas.* $generated_attr_lemmas.*
 
 # At least one of the Xerox or HFST tests failed:
